### ISSUE TITLE
Making the date time automatically use today

### ISSUE THREAD

**Issue by nonlaminar** [Zaku71/Astronomy-Final-Project#6]
I noticed line 61 you used the `datetime` library to get a date specifically! That is so awesome. Adding the date time library is tricky, and you did a great job! However I also noticed that you had it in the format:
```
d1 = datetime(2022,5,8,15,20,15)
```
which will give you exactly that date, and if that is your goal then keep it that way! But if you want your code to utilize today's date and current time, you can use:
```
d1 = datetime.today()
```
Which will use your computers system time to figure out what day it is and what time.
Additionally, if you are feeling up to it, (its kinda dense) the datetime documentation is linked [here](https://docs.python.org/3/library/datetime.html)
Let me know if you have any other questions!

**Comment by Zaku71** [comment]
Thank you so much!!
